# Generated by Django 4.1.2 on 2022-10-22 04:05

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
