# Generated by Django 4.1.2 on 2022-10-26 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('living_room', '0002_alter_room_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='room',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
